/*******************************************************************************
 * Copyright (c) 2016-2019, 2021-2022, 2024-2026 Genome Research Ltd.
 *
 * Author: Sendu Bala <sb10@sanger.ac.uk>
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

package jobqueue

// This file contains some general utility functions for use by client and
// server.

import (
	"bufio"
	"bytes"
	"compress/zlib"
	"context"
	crand "crypto/rand"
	"crypto/subtle"
	"encoding/base64"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"maps"
	"math/rand"
	"net"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/VertebrateResequencing/wr/internal"
	"github.com/VertebrateResequencing/wr/jobqueue/scheduler"
	"github.com/dgryski/go-farm"
	multierror "github.com/hashicorp/go-multierror"
	"github.com/jpillora/backoff"
	"github.com/shirou/gopsutil/v4/process"
)

// AppName gets used in certain places like naming the base directory of created
// working directories during Client.Execute().
var AppName = "jobqueue" //nolint:gochecknoglobals // configurable package-wide default

// mkHashedLevels is the number of directory levels we create in mkHashedDirs.
const mkHashedLevels = 4

// tokenLength is the fixed size of our authentication token, and
// tokenRandBytes is the number of random bytes that base64-encode to it.
const (
	tokenLength    = 43
	tokenRandBytes = 32
)

const (
	reqSchedSpecialRAM = 924
	reqSchedExtraRAM   = 100
	reqSchedTimeRound  = 30 * time.Minute
)

const (
	// bytesPerKB and bytesPerMB are used to convert reported byte/kB sizes to
	// MB.
	bytesPerKB = 1024
	bytesPerMB = 1024 * 1024

	// mkHashedDirMaxTries is how many times we retry creating a hashed dir when
	// it conflicts with a concurrent rmEmptyDirs.
	mkHashedDirMaxTries = 3
)

// pss is the smaps line prefix scanned by scanSmapsPss.
var pss = []byte("Pss:") //nolint:gochecknoglobals // immutable byte-slice constant

// cr, lf and ellipses get used by stdFilter().
//
//nolint:gochecknoglobals // immutable byte-slice constants
var (
	cr       = []byte("\r")
	lf       = []byte("\n")
	ellipses = []byte("[...]\n")
)

const (
	liveStdRawTailLimit    = 64 * 1024
	liveStdCompressedLimit = 4096
	binarySearchDivisor    = 2
)

var liveTailCompressor = compressedLiveTail //nolint:gochecknoglobals // Test hook for FlushCompressed contention.

// generateToken creates a cryptographically secure pseudorandom URL-safe base64
// encoded string 43 bytes long. Used by the server to create a token passed to
// the caller for subsequent client authentication. If the given file exists
// and contains a single 43 byte string, then that is used as the token instead.
func generateToken(tokenFile string) ([]byte, error) {
	if token, err := os.ReadFile(tokenFile); err == nil && len(token) == tokenLength {
		return token, nil
	}

	b := make([]byte, tokenRandBytes)

	_, err := crand.Read(b)
	if err != nil {
		return nil, err
	}

	token := make([]byte, tokenLength)
	base64.URLEncoding.WithPadding(base64.NoPadding).Encode(token, b)

	return token, err
}

// tokenMatches compares a token supplied by a client with a server token (eg.
// generated by generateToken()) and tells you if they match. Does so in a
// cryptographically secure way (avoiding timing attacks).
func tokenMatches(input, expected []byte) bool {
	result := subtle.ConstantTimeCompare(input, expected)

	return result == 1
}

// byteKey calculates a unique key that describes a byte slice.
func byteKey(b []byte) string {
	l, h := farm.Hash128(b)

	return newHexKey(l, h)
}

// newHexKey returns the 32-character lowercase zero-padded hex form of the two
// uint64 halves, written big-endian with l first then h. This is byte-for-byte
// identical to fmt.Sprintf("%016x%016x", l, h) for all uint64 values, but
// avoids the reflection-based formatting on this hot path. The output is used
// as BoltDB keys, lookup-index keys and Go map keys, so it must never diverge.
func newHexKey(l, h uint64) string {
	var hash [16]byte

	binary.BigEndian.PutUint64(hash[0:8], l)
	binary.BigEndian.PutUint64(hash[8:16], h)

	return hex.EncodeToString(hash[:])
}

// foldCloseErr combines an error returned by closing a resource (named in what,
// eg. "source") into a prior error, returning the result. It is intended for
// use in deferred closers via err = foldCloseErr(err, c.Close(), "name").
func foldCloseErr(prior, closeErr error, what string) error {
	if closeErr == nil {
		return prior
	}

	if prior == nil {
		return closeErr
	}

	return fmt.Errorf("%w (and closing %s failed: %w)", prior, what, closeErr)
}

// copy a file *** should be updated to handle source being on a different
// machine or in an S3-style object store.
func copyFile(source string, dest string) (err error) {
	in, err := os.Open(source)
	if err != nil {
		return err
	}
	defer func() {
		err = foldCloseErr(err, in.Close(), "source")
	}()

	out, err := os.Create(dest)
	if err != nil {
		return err
	}
	defer func() {
		err = foldCloseErr(err, out.Close(), "dest")
	}()

	_, err = io.Copy(out, in)

	return err
}

// compress uses zlib to compress stuff, for transferring big stuff like
// stdout, stderr and environment variables over the network, and for storing
// of same on disk.
func compress(data []byte) ([]byte, error) {
	var compressed bytes.Buffer

	w, err := zlib.NewWriterLevel(&compressed, zlib.BestCompression)
	if err != nil {
		return nil, err
	}

	_, err = w.Write(data)
	if err != nil {
		return nil, err
	}

	err = w.Close()
	if err != nil {
		return nil, err
	}

	return compressed.Bytes(), nil
}

// decompress uses zlib to decompress stuff compressed by compress().
func decompress(compressed []byte) ([]byte, error) {
	b := bytes.NewReader(compressed)

	r, err := zlib.NewReader(b)
	if err != nil {
		return nil, err
	}

	buf := new(bytes.Buffer)

	_, err = buf.ReadFrom(r)
	if err != nil {
		return nil, err
	}

	return buf.Bytes(), err
}

// get the current memory usage of a pid and all its children, relying on modern
// linux /proc/*/smaps (based on http://stackoverflow.com/a/31881979/675083).
func currentMemory(pid int) (int, error) {
	kb, err := scanSmapsPss(pid)
	if err != nil {
		return 0, err
	}

	// convert kB to MB
	mem := int(kb / bytesPerKB) //nolint:gosec // a process's memory in MB comfortably fits in an int

	// recurse for children
	childMem, err := sumChildrenMemory(pid)
	if err != nil {
		return mem, err
	}

	return mem + childMem, nil
}

// ownMemoryMB returns this process's own Pss in MB, excluding any child
// processes. Unlike currentMemory it does NOT walk the process tree (no
// gopsutil Children()/whole-/proc scan), so it is cheap to call on a busy host;
// it is used on the per-job hot path after a job command has already exited,
// where the child sum would be both useless and expensive.
func ownMemoryMB() (int, error) {
	kb, err := scanSmapsPss(os.Getpid())
	if err != nil {
		return 0, err
	}

	// convert kB to MB
	return int(kb / bytesPerKB), nil //nolint:gosec // a process's memory in MB comfortably fits in an int
}

// scanSmapsPss reads /proc/<pid>/smaps and sums the Pss (proportional set size)
// values, in kB.
func scanSmapsPss(pid int) (kb uint64, err error) {
	f, err := os.Open(filepath.Clean(fmt.Sprintf("/proc/%d/smaps", pid)))
	if err != nil {
		return 0, err
	}
	defer func() {
		err = foldCloseErr(err, f.Close(), "smaps")
	}()

	r := bufio.NewScanner(f)
	for r.Scan() {
		line := r.Bytes()
		if !bytes.HasPrefix(line, pss) {
			continue
		}

		var size uint64
		if _, err = fmt.Sscanf(string(line[len(pss):]), "%d", &size); err != nil {
			return 0, err
		}

		kb += size
	}

	return kb, r.Err()
}

// sumChildrenMemory returns the total currentMemory of all the child processes
// of pid (child memory-read failures are ignored).
func sumChildrenMemory(pid int) (int, error) {
	p, err := process.NewProcess(int32(pid)) //nolint:gosec // a pid always fits in an int32
	if err != nil {
		return 0, err
	}

	children, err := p.Children()
	if err != nil && !errors.Is(err, process.ErrorNoChildren) {
		return 0, err
	}

	var mem int

	for _, child := range children {
		childMem, errr := currentMemory(int(child.Pid))
		if errr != nil {
			continue
		}

		mem += childMem
	}

	return mem, nil
}

// get the current disk usage within a directory, in MBs. Optionally, provide a
// map of absolute paths to dirs (within path) that should not be checked.
func currentDisk(path string, ignore ...map[string]bool) (int64, error) {
	var disk int64

	skip := make(map[string]bool)
	if len(ignore) == 1 && len(ignore[0]) > 0 {
		skip = ignore[0]
	}

	dir, err := openManaged(path)
	if err != nil {
		return disk, err
	}
	defer func() {
		err = dir.Close()
	}()

	files, err := dir.Readdir(-1)
	if err != nil {
		return disk, err
	}

	for _, file := range files {
		used, errd := diskForFile(path, file, skip, ignore)
		if errd != nil {
			return disk, errd
		}

		disk += used
	}

	return disk, err
}

// diskForFile returns the disk usage in MB contributed by file (which lives in
// dirPath). Directories are recursed into via currentDisk unless they are in
// skip.
func diskForFile(dirPath string, file os.FileInfo, skip map[string]bool, ignore []map[string]bool) (int64, error) {
	if !file.IsDir() {
		return file.Size() / bytesPerMB, nil
	}

	abs := filepath.Join(dirPath, file.Name())
	if skip[abs] {
		return 0, nil
	}

	return currentDisk(abs, ignore...)
}

// getChildProcesses gets the child processes of the given pid, recursively.
func getChildProcesses(pid int32) ([]*process.Process, error) {
	var children []*process.Process

	p, err := process.NewProcess(pid)
	if err != nil {
		// we ignore errors, since we allow for working on processes that we're in
		// the process of killing
		//nolint:nilerr // deliberately ignore the error for processes being killed
		return children, nil
	}

	children, err = p.Children()
	if err != nil && !errors.Is(err, process.ErrorNoChildren) {
		return children, err
	}

	for _, child := range children {
		theseKids, errk := getChildProcesses(child.Pid)
		if errk != nil {
			continue
		}

		if len(theseKids) > 0 {
			children = append(children, theseKids...)
		}
	}

	return children, nil
}

// this prefixSuffixSaver-related code is taken from os/exec, since they are not
// exported. prefixSuffixSaver is an io.Writer which retains the first N bytes
// and the last N bytes written to it. The Bytes() methods reconstructs it with
// a pretty error message.
type prefixSuffixSaver struct {
	N         int
	prefix    []byte
	suffix    []byte
	suffixOff int
	skipped   int64
}

func (w *prefixSuffixSaver) Write(p []byte) (int, error) {
	lenp := len(p)

	p = w.fill(&w.prefix, p)
	if overage := len(p) - w.N; overage > 0 {
		p = p[overage:]
		w.skipped += int64(overage)
	}

	p = w.fill(&w.suffix, p)
	for len(p) > 0 { // 0, 1, or 2 iterations.
		n := copy(w.suffix[w.suffixOff:], p)
		p = p[n:]
		w.skipped += int64(n)

		w.suffixOff += n
		if w.suffixOff == w.N {
			w.suffixOff = 0
		}
	}

	return lenp, nil
}

func (w *prefixSuffixSaver) fill(dst *[]byte, p []byte) []byte {
	if remain := w.N - len(*dst); remain > 0 {
		add := minInt(len(p), remain)
		*dst = append(*dst, p[:add]...)
		p = p[add:]
	}

	return p
}

func (w *prefixSuffixSaver) Bytes() []byte {
	if w.suffix == nil {
		return w.prefix
	}

	if w.skipped == 0 {
		return append(w.prefix, w.suffix...)
	}

	const omittingMsgLen = 50 // approx length of the "... omitting N bytes ..." message

	var buf bytes.Buffer
	buf.Grow(len(w.prefix) + len(w.suffix) + omittingMsgLen)
	buf.Write(w.prefix)
	buf.WriteString("\n... omitting ")
	buf.WriteString(strconv.FormatInt(w.skipped, 10))
	buf.WriteString(" bytes ...\n")
	buf.Write(w.suffix[w.suffixOff:])
	buf.Write(w.suffix[:w.suffixOff])

	return buf.Bytes()
}

func minInt(a, b int) int {
	if a < b {
		return a
	}

	return b
}

type liveTailSaver struct {
	sync.Mutex
	tail  []byte
	dirty bool
}

func (w *liveTailSaver) Write(p []byte) (int, error) {
	w.Lock()
	defer w.Unlock()

	lenp := len(p)
	if lenp == 0 {
		return 0, nil
	}

	w.dirty = true
	if lenp >= liveStdRawTailLimit {
		w.tail = append(w.tail[:0], p[lenp-liveStdRawTailLimit:]...)

		return lenp, nil
	}

	if overage := len(w.tail) + lenp - liveStdRawTailLimit; overage > 0 {
		copy(w.tail, w.tail[overage:])
		w.tail = w.tail[:len(w.tail)-overage]
	}

	w.tail = append(w.tail, p...)

	return lenp, nil
}

func (w *liveTailSaver) FlushCompressed() []byte {
	w.Lock()

	if !w.dirty {
		w.Unlock()

		return nil
	}

	tail := append([]byte(nil), w.tail...)
	w.tail = w.tail[:0]
	w.dirty = false
	w.Unlock()

	return liveTailCompressor(tail)
}

func compressedLiveTail(tail []byte) []byte {
	compressed, err := compress(tail)
	if err != nil {
		return nil
	}

	if len(compressed) <= liveStdCompressedLimit {
		return compressed
	}

	return compressedLiveTailSuffix(tail)
}

// stdFilter keeps only the first and last line of any contiguous block of \r
// terminated lines (to mostly eliminate progress bars), intended for use with
// stdout/err streaming input, outputting to a prefixSuffixSaver. Because you
// must finish reading from the input before continuing, it returns a channel
// that you should wait to receive an error from (nil if everything workd).
func stdFilter(std io.Reader, out io.Writer) chan error {
	reader := bufio.NewReader(std)
	done := make(chan error)

	go func() {
		var merr *multierror.Error

		for {
			p, err := reader.ReadBytes('\n')

			writeFilteredBlock(out, bytes.Split(p, cr), &merr)

			if err != nil {
				break
			}
		}

		done <- merr.ErrorOrNil()
	}()

	return done
}

// stdFilter constants for interpreting a \r-split block of input: blocks of
// more than 1 \r-terminated line have their first and last lines kept, and
// blocks of more than 2 also get an ellipses to show lines were dropped.
const (
	stdFilterKeepLastMin = 2
	stdFilterEllipsesMin = 3
)

// writeFilteredBlock writes the kept lines of a single \r-split block to out,
// appending any write errors to merr. It keeps only the first and last line of
// the block (see stdFilter).
func writeFilteredBlock(out io.Writer, lines [][]byte, merr **multierror.Error) {
	writeStd(out, lines[0], merr)

	if len(lines) <= stdFilterKeepLastMin {
		return
	}

	writeStd(out, lf, merr)

	if len(lines) > stdFilterEllipsesMin {
		writeStd(out, ellipses, merr)
	}

	writeStd(out, lines[len(lines)-2], merr)
	writeStd(out, lf, merr)
}

// writeStd writes b to out, appending any error to merr.
func writeStd(out io.Writer, b []byte, merr **multierror.Error) {
	if _, err := out.Write(b); err != nil {
		*merr = multierror.Append(*merr, err)
	}
}

// envOverride deals with values you get from os.Environ, overriding one set
// with values from another. Returns the new slice of environment variables.
func envOverride(orig []string, over []string) []string {
	override := make(map[string]string)

	for _, envvar := range over {
		pair := strings.Split(envvar, "=")
		override[pair[0]] = envvar
	}

	env := orig
	for i, envvar := range env {
		pair := strings.Split(envvar, "=")
		if replace, do := override[pair[0]]; do {
			env[i] = replace

			delete(override, pair[0])
		}
	}

	for _, envvar := range override {
		env = append(env, envvar)
	}

	return env
}

func compressedLiveTailSuffix(tail []byte) []byte {
	low := 1
	high := len(tail)

	var best []byte

	for low <= high {
		mid := low + (high-low)/binarySearchDivisor

		compressed, err := compress(tail[len(tail)-mid:])
		if err != nil {
			return nil
		}

		if len(compressed) <= liveStdCompressedLimit {
			best = compressed
			low = mid + 1

			continue
		}

		high = mid - 1
	}

	return best
}

// calculateHashedDir returns the hashed directory structure corresponding to
// a given string. Returns dirs rooted at baseDir, and a leaf name.
func calculateHashedDir(baseDir, tohash string) (string, string) {
	dirs := strings.SplitN(tohash, "", mkHashedLevels)
	dirs, leaf := dirs[0:mkHashedLevels-1], dirs[mkHashedLevels-1]
	dirs = append([]string{baseDir}, dirs...)

	return filepath.Join(dirs...), leaf
}

// mkHashedDir uses tohash (which should be a 32 char long string from
// byteKey()) to create a folder nested within baseDir, and in that folder
// creates 2 folders called cwd and tmp, which it returns. Returns an error if
// there were problems making the directories.
func mkHashedDir(baseDir, tohash string) (cwd, tmpDir string, err error) {
	dir, leaf := calculateHashedDir(filepath.Join(baseDir, AppName+"_cwd"), tohash)

	holdFile := filepath.Join(dir, ".hold")
	defer func() {
		err = removeHoldFile(holdFile, err)
	}()

	if err = mkHeldDir(dir, holdFile); err != nil {
		return cwd, tmpDir, err
	}

	// if tohash is a job key then we expect that only 1 of that job is
	// running at any one time per jobqueue, but there could be multiple users
	// running the same cmd, or this user could be running the same command in
	// multiple queues, so we must still create a unique dir at the leaf of our
	// hashed dir structure, to avoid any conflict of multiple processes using
	// the same working directory
	dir, err = os.MkdirTemp(dir, leaf)
	if err != nil {
		return cwd, tmpDir, err
	}

	return mkCwdAndTmp(dir)
}

// holdFilePerm is the permission used for the hold file dropped by mkHeldDir.
const holdFilePerm = 0o600

// removeHoldFile removes the hold file created by mkHeldDir, folding any removal
// error into the given prior error.
func removeHoldFile(holdFile string, prior error) error {
	errr := removeManaged(holdFile)
	if errr == nil || os.IsNotExist(errr) {
		return prior
	}

	if prior == nil {
		return errr
	}

	return fmt.Errorf("%w (and removing the hold file failed: %w)", prior, errr)
}

// mkHeldDir creates dir (retrying a few times in case a concurrent rmEmptyDirs
// conflicts with us) and drops a hold file in it so rmEmptyDirs will not
// immediately remove it.
func mkHeldDir(dir, holdFile string) error {
	tries := 0

	for {
		retry, err := tryMkHeldDir(dir, holdFile, &tries)
		if err != nil {
			return err
		}

		if !retry {
			return nil
		}
	}
}

// The *Managed helpers wrap os file operations on paths that the jobqueue
// itself created and manages (a Job's working/cache dirs, our own /proc
// entries). The paths are trusted by design and cleaned before use, which also
// satisfies gosec's path-traversal analysis without per-call suppressions.

// removeAllManaged is os.RemoveAll for a jobqueue-managed path.
func removeAllManaged(path string) error {
	return os.RemoveAll(filepath.Clean(path))
}

// removeManaged is os.Remove for a jobqueue-managed path.
func removeManaged(path string) error {
	return os.Remove(filepath.Clean(path))
}

// openManaged is os.Open for a jobqueue-managed path.
func openManaged(path string) (*os.File, error) {
	return os.Open(filepath.Clean(path))
}

// mkdirManaged is os.Mkdir for a jobqueue-managed path.
func mkdirManaged(path string, perm os.FileMode) error {
	return os.Mkdir(filepath.Clean(path), perm)
}

// mkdirAllManaged is os.MkdirAll for a jobqueue-managed path.
func mkdirAllManaged(path string, perm os.FileMode) error {
	return os.MkdirAll(filepath.Clean(path), perm)
}

// openFileManaged is os.OpenFile for a jobqueue-managed path.
func openFileManaged(path string, flag int, perm os.FileMode) (*os.File, error) {
	return os.OpenFile(filepath.Clean(path), flag, perm)
}

// tryMkHeldDir makes one attempt to create dir and its hold file. It returns
// retry=true if mkHeldDir should loop again, or an error if we've run out of
// retries. retry=false with a nil error means success.
func tryMkHeldDir(dir, holdFile string, tries *int) (retry bool, err error) {
	if err = mkdirAllManaged(dir, os.ModePerm); err != nil {
		return retryOrFail(tries, err)
	}

	*tries = 0

	f, err := openFileManaged(holdFile, os.O_RDONLY|os.O_CREATE, holdFilePerm)
	if err != nil {
		return retryOrFail(tries, err)
	}

	return false, f.Close()
}

// retryOrFail increments *tries and reports whether the caller should retry
// (still within mkHashedDirMaxTries). When not retrying it returns err so the
// caller can return it.
func retryOrFail(tries *int, err error) (bool, error) {
	*tries++
	if *tries <= mkHashedDirMaxTries {
		return true, nil
	}

	return false, err
}

// mkCwdAndTmp creates "cwd" and "tmp" dirs within dir, returning their paths.
func mkCwdAndTmp(dir string) (cwd, tmpDir string, err error) {
	cwd = filepath.Join(dir, "cwd")
	if err = mkdirManaged(cwd, os.ModePerm); err != nil {
		return cwd, tmpDir, err
	}

	tmpDir = filepath.Join(dir, "tmp")

	return cwd, tmpDir, mkdirManaged(tmpDir, os.ModePerm)
}

// errNotBelowBaseDir is returned when we're asked to delete a directory that is
// not inside the base directory that bounds the deletion.
var errNotBelowBaseDir = errors.New("dir is not below the base dir")

// rmEmptyDirs deletes leafDir and it's parent directories if they are empty,
// stopping before it reaches baseDir (leaving that, and everything above it,
// undeleted). It's ok if leafDir doesn't exist.
//
// leafDir must be a proper descendant of baseDir; otherwise nothing at all is
// deleted and errNotBelowBaseDir is returned. There is no safe upward walk to
// do from anywhere else: with leafDir == baseDir the first parent considered
// would already be above baseDir, and the walk would then delete the empty
// ancestors of the directory tree we were supposed to stay inside.
func rmEmptyDirs(leafDir, baseDir string) error {
	if !dirIsBelow(leafDir, baseDir) {
		return fmt.Errorf("%w: %s vs %s", errNotBelowBaseDir, leafDir, baseDir)
	}

	err := removeManaged(leafDir)
	if err != nil && !os.IsNotExist(err) {
		// *** not sure where the "directory not empty" string comes from;
		// probably not cross platform!
		if strings.Contains(err.Error(), "directory not empty") {
			return nil
		}

		return err
	}

	rmEmptyParentDirs(leafDir, baseDir)

	return nil
}

// rmEmptyParentDirs removes the empty parent directories of leafDir, stopping
// when the next parent would be baseDir or outside it, or when it hits a dir it
// cannot remove (which is expected when another Job is running from the same
// Cwd, so the error is ignored).
func rmEmptyParentDirs(leafDir, baseDir string) {
	current := leafDir

	for {
		parent := filepath.Dir(current)
		if !dirIsBelow(parent, baseDir) || removeManaged(parent) != nil {
			return
		}

		current = parent
	}
}

// dirIsBelow tells you if dir is a proper descendant of baseDir, ie. strictly
// inside it. Both are first made absolute, cleaned and symlink-resolved, so an
// unclean or relative path, or a symlink that really points elsewhere, can't
// sneak past. Equal paths give false, as does anything that can't be resolved,
// so a true result can be treated as permission to delete dir.
func dirIsBelow(dir, baseDir string) bool {
	if dir == "" || baseDir == "" {
		return false
	}

	absDir, err := resolvedAbsPath(dir)
	if err != nil {
		return false
	}

	absBase, err := resolvedAbsPath(baseDir)
	if err != nil {
		return false
	}

	rel, err := filepath.Rel(absBase, absDir)

	return err == nil && relIsBelow(rel)
}

// relIsBelow tells you if a relative path produced by filepath.Rel describes
// somewhere strictly inside the dir it is relative to.
func relIsBelow(rel string) bool {
	return rel != "." && rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator))
}

// resolvedAbsPath returns path as an absolute cleaned path with its symlinks
// resolved. Since path, or the deeper parts of it, may not exist (eg. it has
// already been deleted), it resolves the deepest ancestor that does exist and
// appends the remainder to that.
func resolvedAbsPath(path string) (string, error) {
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}

	rest := ""

	for current := abs; ; current = filepath.Dir(current) {
		resolved, errEval := filepath.EvalSymlinks(current)
		if errEval == nil {
			return filepath.Join(resolved, rest), nil
		}

		if !os.IsNotExist(errEval) {
			return "", errEval
		}

		if filepath.Dir(current) == current {
			return abs, nil
		}

		rest = filepath.Join(filepath.Base(current), rest)
	}
}

// removeAllExcept deletes the contents of a given directory (absolute path),
// except for the given folders (relative paths).
func removeAllExcept(path string, exceptions []string) error {
	keepDirs := make(map[string]bool)
	checkDirs := make(map[string]bool)

	path = filepath.Clean(path)
	for _, dir := range exceptions {
		abs := filepath.Join(path, dir)
		keepDirs[abs] = true

		parent := filepath.Dir(abs)
		for parent != path {
			checkDirs[parent] = true
			parent = filepath.Dir(parent)
		}
	}

	return removeWithExceptions(path, keepDirs, checkDirs)
}

// removeWithExceptions is the recursive part of removeAllExcept's
// implementation that does the real work of deleting stuff.
func removeWithExceptions(path string, keepDirs map[string]bool, checkDirs map[string]bool) error {
	entries, errr := os.ReadDir(path)
	if errr != nil {
		return errr
	}

	for _, entry := range entries {
		if err := removeEntryWithExceptions(filepath.Join(path, entry.Name()), entry.IsDir(),
			keepDirs, checkDirs); err != nil {
			return err
		}
	}

	return nil
}

// removeEntryWithExceptions handles a single entry for removeWithExceptions:
// files are removed, kept dirs are left, dirs containing exceptions are
// recursed into, and other dirs are removed entirely.
func removeEntryWithExceptions(abs string, isDir bool, keepDirs, checkDirs map[string]bool) error {
	switch {
	case !isDir:
		return removeManaged(abs)
	case keepDirs[abs]:
		return nil
	case checkDirs[abs]:
		return removeWithExceptions(abs, keepDirs, checkDirs)
	default:
		return removeAllManaged(abs)
	}
}

// compressFile reads the content of the given file then compresses that. Since
// this happens in memory, only suitable for small files!
func compressFile(path string) ([]byte, error) {
	path = internal.TildaToHome(path)

	content, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	return compress(content)
}

// reqForScheduler takes a job's Requirements and returns a possibly modified
// version if using less than 924MB memory to have +100MB memory to allow some
// leeway in case the job scheduler calculates used memory differently, and for
// other memory usage vagaries. It also rounds up the Time to the nearest half
// hour.
func reqForScheduler(req *scheduler.Requirements) *scheduler.Requirements {
	ram := req.RAM
	if ram < reqSchedSpecialRAM {
		ram += reqSchedExtraRAM
	}

	d := req.Time.Round(reqSchedTimeRound)
	if d < req.Time {
		d += reqSchedTimeRound
	}

	out := &scheduler.Requirements{
		RAM:   ram,
		Time:  d,
		Cores: req.Cores,
		Disk:  req.Disk,
	}

	if len(req.Other) > 0 {
		out.Other = make(map[string]string, len(req.Other))
		maps.Copy(out.Other, req.Other)
	}

	return out
}

// calculateItemDelay returns a delay based on a backoff and the number of
// previous delays. delayMin is the minimum delay (the server's resolved
// ReleaseDelayMin).
func calculateItemDelay(numPreviousDelays int, delayMin time.Duration) time.Duration {
	b := &backoff.Backoff{
		Min:    delayMin,
		Max:    ClientReleaseDelayMax,
		Factor: ClientReleaseDelayStepFactor,
		Jitter: false, // don't like the behaviour of it's jitter
	}

	d := b.ForAttempt(float64(numPreviousDelays))
	d -= time.Duration(rand.Float64()*float64(delayMin) - float64(delayMin)) // #nosec

	if d < 0 {
		d = ClientReleaseDelayMax
	}

	return d
}

// fqdn returns the fully qualified domain name of the current host, or
// "localhost" or just the hostname on error.
func fqdn(ctx context.Context) string {
	hostname, err := os.Hostname()
	if err != nil {
		return localhost
	}

	fqdn, err := net.DefaultResolver.LookupCNAME(ctx, hostname)
	if err != nil {
		fqdn = hostname
	}

	return strings.TrimSuffix(fqdn, ".")
}
