run:
  deadline: 4m
  build-tags:
    - netgo
  skip-files:
    - jobqueue/static.go
  modules-download-mode: readonly

output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: true
  govet:
    check-shadowing: true
  unused:
    # treat code as a program (not a library) and report unused exported identifiers; default is false.
    # XXX: if you enable this setting, unused will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find funcs usages. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    check-exported: false
  unparam:
    # Inspect exported functions, default is false. Set to true if no external program/library imports your code.
    # XXX: if you enable this setting, unparam will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find external interfaces. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 10
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 100

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - goimports
    - golint
    - gomnd
    - gosec
    - ifshort
    - importas
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - rowserrcheck
    - stylecheck
    - thelper
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wsl
  # disable:
  #   - asciicheck
  #   - bodyclose
  #   - depguard
  #   - exhaustive
  #   - exhaustivestruct
  #   - gofmt
  #   - gofumpt
  #   - goheader
  #   - gomoddirectives
  #   - gomodguard
  #   - goprintffuncname
  #   - interfacer
  #   - maligned
  #   - paralleltest
  #   - promlinter
  #   - revive
  #   - sqlclosecheck
  #   - tagliatelle
  #   - testpackage
  #   - tparallel
  #   - wrapcheck

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gochecknoglobals
        - gochecknoinits
    - path: cmd/
      linters:
        - gocyclo
        - dupl
        - gochecknoglobals
        - gochecknoinits
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: master

