run:
  deadline: 4m
  build-tags:
    - netgo
  skip-files:
    - jobqueue/static.go
  modules-download-mode: readonly

output:
  format: colored-line-number

linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 10
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 100

linters:
  disable-all: true
  enable-all: false
  enable:
    - dupl
    - gocyclo
    - gochecknoglobals
    - gochecknoinits

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gochecknoglobals
        - gochecknoinits
    - path: cmd/
      linters:
        - gocyclo
        - dupl
        - gochecknoglobals
        - gochecknoinits

  new-from-rev: master

