author: Sendu Bala
description: Software Workflow Runner
os: darwin linux
includes:
  - README.md
  - CHANGELOG.md
  - LICENSE
  - wr_config.yml
excludes:
  - \.git
script:
  - rm -fr vendor
  - CGO_ENABLED=0 dep ensure
  - CGO_ENABLED=0 go build -tags netgo -ldflags "-X github.com/VertebrateResequencing/wr/cmd.wrVersion=`git describe --tags --always --long --dirty`"
