author: Sendu Bala
description: Software Workflow Runner
os: darwin linux
includes:
  - README.md
  - LICENSE
  - wr_config.yml
excludes:
  - \.git
script:
  - go get -tags netgo -v
  - go build -tags netgo -ldflags "-X github.com/VertebrateResequencing/wr/cmd.wrVersion=`git describe --tags --always --long --dirty`"
