---
before_install:
  - "go get github.com/modocache/gover"
  - "go get github.com/mattn/goveralls"
cache:
  directories:
    - $HOME/go/pkg/
dist: trusty
env:
  global:
    - GO111MODULE=on
go:
  - "1.16.3"
go_import_path: github.com/VertebrateResequencing/wr
install:
  - "go mod verify"
jobs:
  include:
    -
      script:
        - "go test -mod=mod -tags netgo -coverprofile=main.coverprofile -covermode count -failfast ./ || travis_terminate 1"
        - "go test -mod=mod -tags netgo -coverprofile=queue.coverprofile -covermode count -failfast ./queue || travis_terminate 1"
        - "go test -mod=mod -tags netgo -coverprofile=sched.coverprofile -covermode count -failfast ./jobqueue/scheduler || travis_terminate 1"
        - "go test -mod=mod -tags netgo -v -coverprofile=jq.coverprofile -covermode count -failfast ./jobqueue || travis_terminate 1"
        - "go test -mod=mod -tags netgo -coverprofile=cloud.coverprofile -covermode count -failfast ./cloud || travis_terminate 1"
        - "go test -mod=mod -tags netgo -coverprofile=rp.coverprofile -covermode count -failfast ./rp || travis_terminate 1"
        - "$HOME/gopath/bin/gover || travis_terminate 1"
        - "$HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci"
      stage: Tests
language: go
