name: tests

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WR_TESTSUITE_MAX_PARALLEL: 4
      WR_TESTSUITE_TIMINGS: 1

    steps:
    - uses: actions/checkout@v7.0.0
    
    - name: Setup Go
      uses: actions/setup-go@v6.4.0
      with:
        go-version-file: go.mod

    - name: Install container runtimes
      run: |
        sudo apt-get update
        sudo apt-get install -y singularity-container
        docker version
        singularity --version

    - name: Run tests
      run: make test

    - name: Run tests with race detection
      run: make race
